services:
  mysql2:
    image: mysql
    ports:
      - "3309:3306"
    expose:
      - "3309"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=123