services:
  mysql:
    image: mysql
    ports:
      - "3308:3306"
    expose:
      - "3308"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=123